services:
  passcore:
    build: .
    container_name: passcore-nitap-gc
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - ad-net


networks:
  ad-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/16